# Generated by Django 5.1.1 on 2024-09-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_note_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="image",
        ),
    ]
