# Generated by Django 5.1.1 on 2024-09-08 14:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_note_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(
                default="posts/default.jpg",
                verbose_name="Image",
            ),
        ),
    ]
